/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user account
         * @description Creates a new user account. Use ?useCookies=true to set HttpOnly auth cookies for browser clients.
         */
        post: operations["Register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login with email and password
         * @description Authenticates user and returns tokens. Use ?useCookies=true to set HttpOnly auth cookies for browser clients.
         */
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout and clear authentication
         * @description Clears auth cookies and optionally revokes refresh token. Use revokeAllSessions=true to logout from all devices.
         */
        post: operations["Logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token using refresh token
         * @description Refreshes access token. Use ?useCookies=true to update HttpOnly auth cookies for browser clients. Refresh token can be provided in request body or will be read from cookie.
         */
        post: operations["RefreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user profile */
        get: operations["GetCurrentUser"];
        /**
         * Update current user profile
         * @description Updates user profile fields (first name, last name). Changes are tracked in audit logs with before/after diff.
         */
        put: operations["UpdateUserProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/trail/{correlationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get complete audit trail for a correlation ID */
        get: operations["GetAuditTrail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/entity/{entityType}/{entityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get change history for a specific entity */
        get: operations["GetEntityHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get paginated HTTP request audit logs with filtering */
        get: operations["GetHttpRequestAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/handlers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get paginated handler audit logs with filtering */
        get: operations["GetHandlerAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export audit logs to CSV or JSON for compliance reporting
         * @description Maximum 100,000 rows per export. Date range limited to 90 days. Requires at least one filter.
         */
        get: operations["ExportAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get paginated list of roles */
        get: operations["GetRoles"];
        put?: never;
        /** Create a new role */
        post: operations["CreateRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get role by ID with permissions */
        get: operations["GetRoleById"];
        /** Update role name */
        put: operations["UpdateRole"];
        post?: never;
        /** Delete a role */
        delete: operations["DeleteRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/{roleId}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get permissions assigned to a role */
        get: operations["GetRolePermissions"];
        /** Assign permissions to a role */
        put: operations["AssignPermissionsToRole"];
        post?: never;
        /** Remove permissions from a role */
        delete: operations["RemovePermissionsFromRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get paginated list of users */
        get: operations["GetUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by ID */
        get: operations["GetUserById"];
        /** Update user details */
        put: operations["UpdateUser"];
        post?: never;
        /** Soft-delete a user (locks account) */
        delete: operations["DeleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get roles assigned to a user */
        get: operations["GetUserRoles"];
        /** Assign roles to a user (replaces existing) */
        put: operations["AssignRolesToUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get effective permissions for a user */
        get: operations["GetUserPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AssignPermissionToRoleCommand: {
            roleId: string;
            permissions: string[];
            operationType?: components["schemas"]["AuditOperationType"];
        };
        AssignRolesToUserCommand: {
            userId: string;
            roleNames: string[];
            operationType?: components["schemas"]["AuditOperationType"];
        };
        AuditOperationType: number;
        AuditTrailDto: {
            correlationId: string;
            httpRequest: null | components["schemas"]["HttpRequestAuditDetailDto"];
            handlers: components["schemas"]["HandlerAuditDto"][];
            entityChanges: components["schemas"]["EntityAuditDto"][];
        };
        AuthResponse: {
            userId: string;
            email: string;
            accessToken: string;
            refreshToken: string;
            /** Format: date-time */
            expiresAt: string;
        };
        CreateRoleCommand: {
            name: string;
            permissions?: null | string[];
            operationType?: components["schemas"]["AuditOperationType"];
        };
        CurrentUserDto: {
            id: string;
            email: string;
            firstName: null | string;
            lastName: null | string;
            fullName: string;
            roles: string[];
            tenantId: null | string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        EntityAuditDto: {
            /** Format: uuid */
            id: string;
            entityType: string;
            entityId: string;
            operation: string;
            entityDiff: null | string;
            /** Format: date-time */
            timestamp: string;
            /** Format: int32 */
            version: number | string;
        };
        EntityHistoryDto: {
            entityType: string;
            entityId: string;
            history: components["schemas"]["EntityHistoryEntryDto"][];
        };
        EntityHistoryEntryDto: {
            /** Format: uuid */
            id: string;
            operation: string;
            entityDiff: null | string;
            /** Format: date-time */
            timestamp: string;
            /** Format: int32 */
            version: number | string;
            correlationId: string;
            handlerName: null | string;
            userId: null | string;
            userEmail: null | string;
        };
        HandlerAuditDto: {
            /** Format: uuid */
            id: string;
            handlerName: string;
            operationType: string;
            targetDtoType: null | string;
            targetDtoId: null | string;
            dtoDiff: null | string;
            inputParameters: null | string;
            outputResult: null | string;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: null | string;
            /** Format: int64 */
            durationMs: null | number | string;
            isSuccess: boolean;
            errorMessage: null | string;
            entityChanges: components["schemas"]["EntityAuditDto"][];
        };
        HttpRequestAuditDetailDto: {
            /** Format: uuid */
            id: string;
            correlationId: string;
            httpMethod: string;
            url: string;
            queryString: null | string;
            requestHeaders: null | string;
            requestBody: null | string;
            /** Format: int32 */
            responseStatusCode: null | number | string;
            responseBody: null | string;
            userId: null | string;
            userEmail: null | string;
            tenantId: null | string;
            ipAddress: null | string;
            userAgent: null | string;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: null | string;
            /** Format: int64 */
            durationMs: null | number | string;
            handlers: components["schemas"]["HandlerAuditDto"][];
        };
        HttpRequestAuditDto: {
            /** Format: uuid */
            id: string;
            correlationId: string;
            httpMethod: string;
            url: string;
            /** Format: int32 */
            responseStatusCode: null | number | string;
            userId: null | string;
            userEmail: null | string;
            tenantId: null | string;
            ipAddress: null | string;
            /** Format: date-time */
            startTime: string;
            /** Format: int64 */
            durationMs: null | number | string;
            /** Format: int32 */
            handlerCount: number | string;
            /** Format: int32 */
            entityChangeCount: number | string;
        };
        LoginCommand: {
            email: string;
            password: string;
            /** @default false */
            useCookies: boolean;
        };
        LogoutCommand: {
            refreshToken?: null | string;
            /** @default false */
            revokeAllSessions: boolean;
        };
        PaginatedListOfHandlerAuditDto: {
            items: components["schemas"]["HandlerAuditDto"][];
            /** Format: int32 */
            pageNumber: number | string;
            /** Format: int32 */
            totalPages: number | string;
            /** Format: int32 */
            totalCount: number | string;
            hasPreviousPage?: boolean;
            hasNextPage?: boolean;
        };
        PaginatedListOfHttpRequestAuditDto: {
            items: components["schemas"]["HttpRequestAuditDto"][];
            /** Format: int32 */
            pageNumber: number | string;
            /** Format: int32 */
            totalPages: number | string;
            /** Format: int32 */
            totalCount: number | string;
            hasPreviousPage?: boolean;
            hasNextPage?: boolean;
        };
        PaginatedListOfRoleListDto: {
            items: components["schemas"]["RoleListDto"][];
            /** Format: int32 */
            pageNumber: number | string;
            /** Format: int32 */
            totalPages: number | string;
            /** Format: int32 */
            totalCount: number | string;
            hasPreviousPage?: boolean;
            hasNextPage?: boolean;
        };
        PaginatedListOfUserListDto: {
            items: components["schemas"]["UserListDto"][];
            /** Format: int32 */
            pageNumber: number | string;
            /** Format: int32 */
            totalPages: number | string;
            /** Format: int32 */
            totalCount: number | string;
            hasPreviousPage?: boolean;
            hasNextPage?: boolean;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        RefreshTokenCommand: {
            accessToken: string;
            refreshToken?: null | string;
            /** @default false */
            useCookies: boolean;
        };
        RegisterCommand: {
            email: string;
            password: string;
            firstName: null | string;
            lastName: null | string;
            /** @default false */
            useCookies: boolean;
        };
        RemovePermissionFromRoleCommand: {
            roleId: string;
            permissions: string[];
            operationType?: components["schemas"]["AuditOperationType"];
        };
        RoleDto: {
            id: string;
            name: string;
            normalizedName: null | string;
            /** Format: int32 */
            userCount: number | string;
            permissions: string[];
        };
        RoleListDto: {
            id: string;
            name: string;
            /** Format: int32 */
            userCount: number | string;
        };
        UpdateRoleCommand: {
            roleId: string;
            name: string;
            operationType?: components["schemas"]["AuditOperationType"];
        };
        UpdateUserCommand: {
            userId: string;
            displayName: null | string;
            firstName: null | string;
            lastName: null | string;
            lockoutEnabled: null | boolean;
            operationType?: components["schemas"]["AuditOperationType"];
        };
        UpdateUserProfileCommand: {
            firstName: null | string;
            lastName: null | string;
            operationType?: components["schemas"]["AuditOperationType"];
        };
        UserDto: {
            id: string;
            email: string;
            userName: null | string;
            displayName: null | string;
            firstName: null | string;
            lastName: null | string;
            emailConfirmed: boolean;
            lockoutEnabled: boolean;
            /** Format: date-time */
            lockoutEnd: null | string;
            roles: string[];
        };
        UserListDto: {
            id: string;
            email: string;
            displayName: null | string;
            isLocked: boolean;
            roles: string[];
        };
        UserPermissionsDto: {
            userId: string;
            email: string;
            roles: string[];
            permissions: string[];
        };
        UserProfileDto: {
            id: string;
            email: string;
            firstName: null | string;
            lastName: null | string;
            fullName: string;
            roles: string[];
            tenantId: null | string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            modifiedAt: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Register: {
        parameters: {
            query?: {
                useCookies?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    Login: {
        parameters: {
            query?: {
                useCookies?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    Logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["LogoutCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RefreshToken: {
        parameters: {
            query?: {
                useCookies?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    UpdateUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserProfileCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetAuditTrail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                correlationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditTrailDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetEntityHistory: {
        parameters: {
            query?: {
                pageNumber?: number | string;
                pageSize?: number | string;
            };
            header?: never;
            path: {
                entityType: string;
                entityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityHistoryDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetHttpRequestAuditLogs: {
        parameters: {
            query?: {
                pageNumber?: number | string;
                pageSize?: number | string;
                userId?: string;
                httpMethod?: string;
                statusCode?: number | string;
                fromDate?: string;
                toDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListOfHttpRequestAuditDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetHandlerAuditLogs: {
        parameters: {
            query?: {
                pageNumber?: number | string;
                pageSize?: number | string;
                handlerName?: string;
                operationType?: string;
                isSuccess?: boolean;
                fromDate?: string;
                toDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListOfHandlerAuditDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ExportAuditLogs: {
        parameters: {
            query?: {
                fromDate?: string;
                toDate?: string;
                entityType?: string;
                userId?: string;
                format?: string;
                maxRows?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetRoles: {
        parameters: {
            query?: {
                Search?: string;
                Page?: number | string;
                PageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListOfRoleListDto"];
                };
            };
        };
    };
    CreateRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetRoleById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    UpdateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    DeleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetRolePermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AssignPermissionsToRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignPermissionToRoleCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RemovePermissionsFromRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemovePermissionFromRoleCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetUsers: {
        parameters: {
            query?: {
                Search?: string;
                Role?: string;
                IsLocked?: boolean;
                Page?: number | string;
                PageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListOfUserListDto"];
                };
            };
        };
    };
    GetUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    UpdateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    DeleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetUserRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AssignRolesToUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRolesToUserCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetUserPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPermissionsDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
